# Generated by Django 2.0 on 2018-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=66, verbose_name='站点名称')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='站点描述')),
                ('keywords', models.TextField(blank=True, max_length=150, verbose_name='站点关键词')),
            ],
            options={
                'verbose_name': '管理内容',
                'verbose_name_plural': '站点管理',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=0, verbose_name='显示顺序')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='分类名称')),
                ('link', models.CharField(max_length=20, verbose_name='分类链接')),
            ],
            options={
                'verbose_name': '目录',
                'ordering': ['index'],
                'verbose_name_plural': '目录',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-created_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Friendly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=66, verbose_name='站点名称')),
                ('link', models.CharField(max_length=200, verbose_name='链接')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '友情链接',
                'ordering': ['sort', 'site_name'],
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('excerpt', models.CharField(blank=True, editable=False, max_length=200, verbose_name='摘要')),
                ('fmtType', models.CharField(default='markdown', max_length=20, verbose_name='格式化类型')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('slug', models.CharField(max_length=150, null=True, verbose_name='文章别名')),
            ],
            options={
                'verbose_name': '文章',
                'ordering': ['-created_time', 'title'],
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-created_time', 'name'],
            },
        ),
    ]
