# Generated by Django 2.0 on 2018-01-02 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendly',
            options={'ordering': ['sort', 'site_name'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.RemoveField(
            model_name='blogset',
            name='userAvatar',
        ),
        migrations.RemoveField(
            model_name='friendly',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='blogset',
            name='keywords',
            field=models.TextField(blank=True, max_length=150, verbose_name='站点关键词'),
        ),
        migrations.AddField(
            model_name='friendly',
            name='sort',
            field=models.IntegerField(blank=True, default=0, verbose_name='显示顺序'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='post',
            name='fmtType',
            field=models.CharField(default='markdown', max_length=20, verbose_name='格式化类型'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='blogset',
            name='description',
            field=models.TextField(blank=True, max_length=150, verbose_name='站点描述'),
        ),
    ]
