# Generated by Django 2.0 on 2018-01-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180102_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=150, null=True, verbose_name='文章别名'),
        ),
    ]
