# Generated by Django 2.0 on 2017-12-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171220_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField(max_length=66, verbose_name='站点名称')),
                ('link', models.TextField(max_length=200, verbose_name='链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['-create_time', 'site_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogset',
            options={'verbose_name': '管理内容', 'verbose_name_plural': '站点管理'},
        ),
    ]
