# Generated by Django 2.0 on 2017-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171226_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendly',
            options={'ordering': ['sort', 'site_name'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.RemoveField(
            model_name='friendly',
            name='create_time',
        ),
        migrations.AddField(
            model_name='friendly',
            name='sort',
            field=models.IntegerField(blank=True, default=0, verbose_name='显示顺序'),
        ),
    ]
