# Generated by Django 2.0 on 2017-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171220_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=0, verbose_name='显示顺序')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='分类名称')),
                ('link', models.CharField(max_length=20, verbose_name='分类链接')),
            ],
            options={
                'verbose_name': '分类',
                'ordering': ['index'],
                'verbose_name_plural': '分类',
            },
        ),
        migrations.AlterModelOptions(
            name='friendly',
            options={'ordering': ['create_time', 'site_name'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.AlterField(
            model_name='friendly',
            name='link',
            field=models.CharField(max_length=200, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='friendly',
            name='site_name',
            field=models.CharField(max_length=66, verbose_name='站点名称'),
        ),
    ]
