# Generated by Django 2.0 on 2017-12-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171227_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogset',
            name='UserName',
        ),
        migrations.RemoveField(
            model_name='blogset',
            name='userAvatar',
        ),
        migrations.AddField(
            model_name='blogset',
            name='keywords',
            field=models.TextField(blank=True, max_length=150, verbose_name='站点关键词'),
        ),
        migrations.AlterField(
            model_name='blogset',
            name='description',
            field=models.TextField(blank=True, max_length=150, verbose_name='站点描述'),
        ),
    ]
