# Generated by Django 2.0 on 2018-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='attach',
            name='file_type',
            field=models.CharField(default='image', max_length=25, verbose_name='文件类型'),
        ),
    ]
