# Generated by Django 2.0 on 2017-12-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0002_auto_20171222_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
